// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rasterInfo
SEXP rasterInfo(Rcpp::RObject x, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_rasterInfo(SEXP xSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(rasterInfo(x, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// flattenIndices
SEXP flattenIndices(Rcpp::RObject x, Rcpp::IntegerMatrix locs, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_flattenIndices(SEXP xSEXP, SEXP locsSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(flattenIndices(x, locs, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// expandIndices
SEXP expandIndices(Rcpp::RObject x, Rcpp::NumericVector indices, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_expandIndices(SEXP xSEXP, SEXP indicesSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(expandIndices(x, indices, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// lineSums
SEXP lineSums(Rcpp::RObject x, int dim, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_lineSums(SEXP xSEXP, SEXP dimSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(lineSums(x, dim, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// blockPartition
SEXP blockPartition(Rcpp::RObject x, Rcpp::Nullable<Rcpp::IntegerVector> spatial, double targetElements, int count);
RcppExport SEXP _imply_blockPartition(SEXP xSEXP, SEXP spatialSEXP, SEXP targetElementsSEXP, SEXP countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< double >::type targetElements(targetElementsSEXP);
    Rcpp::traits::input_parameter< int >::type count(countSEXP);
    rcpp_result_gen = Rcpp::wrap(blockPartition(x, spatial, targetElements, count));
    return rcpp_result_gen;
END_RCPP
}
// permuteView
SEXP permuteView(Rcpp::RObject x, Rcpp::IntegerVector order, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_permuteView(SEXP xSEXP, SEXP orderSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type order(orderSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(permuteView(x, order, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// dataAddress
std::string dataAddress(Rcpp::RObject x);
RcppExport SEXP _imply_dataAddress(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dataAddress(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_imply_rasterInfo", (DL_FUNC) &_imply_rasterInfo, 3},
    {"_imply_flattenIndices", (DL_FUNC) &_imply_flattenIndices, 4},
    {"_imply_expandIndices", (DL_FUNC) &_imply_expandIndices, 4},
    {"_imply_lineSums", (DL_FUNC) &_imply_lineSums, 4},
    {"_imply_blockPartition", (DL_FUNC) &_imply_blockPartition, 4},
    {"_imply_permuteView", (DL_FUNC) &_imply_permuteView, 4},
    {"_imply_dataAddress", (DL_FUNC) &_imply_dataAddress, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_imply(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
