// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// applyOverMargin
Rcpp::List applyOverMargin(Rcpp::RObject x, Rcpp::IntegerVector margin, Rcpp::Function fun, Rcpp::Nullable<Rcpp::List> callNames, bool simplify);
RcppExport SEXP _imply_applyOverMargin(SEXP xSEXP, SEXP marginSEXP, SEXP funSEXP, SEXP callNamesSEXP, SEXP simplifySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type margin(marginSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type fun(funSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type callNames(callNamesSEXP);
    Rcpp::traits::input_parameter< bool >::type simplify(simplifySEXP);
    rcpp_result_gen = Rcpp::wrap(applyOverMargin(x, margin, fun, callNames, simplify));
    return rcpp_result_gen;
END_RCPP
}
// orientationFromXform
std::string orientationFromXform(Rcpp::NumericMatrix xform);
RcppExport SEXP _imply_orientationFromXform(SEXP xformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xform(xformSEXP);
    rcpp_result_gen = Rcpp::wrap(orientationFromXform(xform));
    return rcpp_result_gen;
END_RCPP
}
// invertXform
Rcpp::NumericMatrix invertXform(Rcpp::NumericMatrix xform);
RcppExport SEXP _imply_invertXform(SEXP xformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xform(xformSEXP);
    rcpp_result_gen = Rcpp::wrap(invertXform(xform));
    return rcpp_result_gen;
END_RCPP
}
// pointsToVoxel
Rcpp::NumericMatrix pointsToVoxel(Rcpp::NumericMatrix locs, Rcpp::NumericMatrix xform, Rcpp::NumericVector pixdim, std::string type);
RcppExport SEXP _imply_pointsToVoxel(SEXP locsSEXP, SEXP xformSEXP, SEXP pixdimSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xform(xformSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pixdim(pixdimSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(pointsToVoxel(locs, xform, pixdim, type));
    return rcpp_result_gen;
END_RCPP
}
// pointsFromVoxel
Rcpp::NumericMatrix pointsFromVoxel(Rcpp::NumericMatrix locs, Rcpp::NumericMatrix xform, Rcpp::NumericVector pixdim, std::string type);
RcppExport SEXP _imply_pointsFromVoxel(SEXP locsSEXP, SEXP xformSEXP, SEXP pixdimSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xform(xformSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pixdim(pixdimSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(pointsFromVoxel(locs, xform, pixdim, type));
    return rcpp_result_gen;
END_RCPP
}
// roundPoints
Rcpp::NumericMatrix roundPoints(Rcpp::NumericMatrix locs, std::string round, Rcpp::Nullable<Rcpp::NumericVector> bounds);
RcppExport SEXP _imply_roundPoints(SEXP locsSEXP, SEXP roundSEXP, SEXP boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< std::string >::type round(roundSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type bounds(boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(roundPoints(locs, round, bounds));
    return rcpp_result_gen;
END_RCPP
}
// rasterInfo
SEXP rasterInfo(Rcpp::RObject x, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_rasterInfo(SEXP xSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(rasterInfo(x, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// flattenIndices
SEXP flattenIndices(Rcpp::RObject x, Rcpp::IntegerMatrix locs, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_flattenIndices(SEXP xSEXP, SEXP locsSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(flattenIndices(x, locs, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// expandIndices
SEXP expandIndices(Rcpp::RObject x, Rcpp::NumericVector indices, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_expandIndices(SEXP xSEXP, SEXP indicesSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(expandIndices(x, indices, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// lineSums
SEXP lineSums(Rcpp::RObject x, int dim, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_lineSums(SEXP xSEXP, SEXP dimSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(lineSums(x, dim, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// blockPartition
SEXP blockPartition(Rcpp::RObject x, Rcpp::Nullable<Rcpp::IntegerVector> spatial, double targetElements, int count);
RcppExport SEXP _imply_blockPartition(SEXP xSEXP, SEXP spatialSEXP, SEXP targetElementsSEXP, SEXP countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< double >::type targetElements(targetElementsSEXP);
    Rcpp::traits::input_parameter< int >::type count(countSEXP);
    rcpp_result_gen = Rcpp::wrap(blockPartition(x, spatial, targetElements, count));
    return rcpp_result_gen;
END_RCPP
}
// permuteView
SEXP permuteView(Rcpp::RObject x, Rcpp::IntegerVector order, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_permuteView(SEXP xSEXP, SEXP orderSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type order(orderSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(permuteView(x, order, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// dataAddress
std::string dataAddress(Rcpp::RObject x);
RcppExport SEXP _imply_dataAddress(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dataAddress(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_imply_applyOverMargin", (DL_FUNC) &_imply_applyOverMargin, 5},
    {"_imply_orientationFromXform", (DL_FUNC) &_imply_orientationFromXform, 1},
    {"_imply_invertXform", (DL_FUNC) &_imply_invertXform, 1},
    {"_imply_pointsToVoxel", (DL_FUNC) &_imply_pointsToVoxel, 4},
    {"_imply_pointsFromVoxel", (DL_FUNC) &_imply_pointsFromVoxel, 4},
    {"_imply_roundPoints", (DL_FUNC) &_imply_roundPoints, 3},
    {"_imply_rasterInfo", (DL_FUNC) &_imply_rasterInfo, 3},
    {"_imply_flattenIndices", (DL_FUNC) &_imply_flattenIndices, 4},
    {"_imply_expandIndices", (DL_FUNC) &_imply_expandIndices, 4},
    {"_imply_lineSums", (DL_FUNC) &_imply_lineSums, 4},
    {"_imply_blockPartition", (DL_FUNC) &_imply_blockPartition, 4},
    {"_imply_permuteView", (DL_FUNC) &_imply_permuteView, 4},
    {"_imply_dataAddress", (DL_FUNC) &_imply_dataAddress, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_imply(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
