// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/imply.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// applyOverMargin
Rcpp::List applyOverMargin(Rcpp::RObject x, Rcpp::IntegerVector margin, Rcpp::Function fun, Rcpp::Nullable<Rcpp::List> callNames, bool simplify, double from, double to, Rcpp::Nullable<Rcpp::Function> progress, double reportEvery);
RcppExport SEXP _imply_applyOverMargin(SEXP xSEXP, SEXP marginSEXP, SEXP funSEXP, SEXP callNamesSEXP, SEXP simplifySEXP, SEXP fromSEXP, SEXP toSEXP, SEXP progressSEXP, SEXP reportEverySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type margin(marginSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type fun(funSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type callNames(callNamesSEXP);
    Rcpp::traits::input_parameter< bool >::type simplify(simplifySEXP);
    Rcpp::traits::input_parameter< double >::type from(fromSEXP);
    Rcpp::traits::input_parameter< double >::type to(toSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::Function> >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< double >::type reportEvery(reportEverySEXP);
    rcpp_result_gen = Rcpp::wrap(applyOverMargin(x, margin, fun, callNames, simplify, from, to, progress, reportEvery));
    return rcpp_result_gen;
END_RCPP
}
// applyOverMarginPacked
Rcpp::List applyOverMarginPacked(Rcpp::RawVector values, std::string type, Rcpp::IntegerVector dim, Rcpp::IntegerVector margin, Rcpp::Function fun, double slope, double intercept, Rcpp::Nullable<Rcpp::List> callNames, bool simplify, double from, double to, Rcpp::Nullable<Rcpp::Function> progress, double reportEvery);
RcppExport SEXP _imply_applyOverMarginPacked(SEXP valuesSEXP, SEXP typeSEXP, SEXP dimSEXP, SEXP marginSEXP, SEXP funSEXP, SEXP slopeSEXP, SEXP interceptSEXP, SEXP callNamesSEXP, SEXP simplifySEXP, SEXP fromSEXP, SEXP toSEXP, SEXP progressSEXP, SEXP reportEverySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type margin(marginSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type fun(funSEXP);
    Rcpp::traits::input_parameter< double >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< double >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type callNames(callNamesSEXP);
    Rcpp::traits::input_parameter< bool >::type simplify(simplifySEXP);
    Rcpp::traits::input_parameter< double >::type from(fromSEXP);
    Rcpp::traits::input_parameter< double >::type to(toSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::Function> >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< double >::type reportEvery(reportEverySEXP);
    rcpp_result_gen = Rcpp::wrap(applyOverMarginPacked(values, type, dim, margin, fun, slope, intercept, callNames, simplify, from, to, progress, reportEvery));
    return rcpp_result_gen;
END_RCPP
}
// applyOverMarginSparse
Rcpp::List applyOverMarginSparse(Rcpp::RawVector mask, Rcpp::RObject values, Rcpp::IntegerVector dim, int spatial, Rcpp::IntegerVector margin, Rcpp::Function fun, Rcpp::Nullable<Rcpp::List> callNames, bool simplify, double from, double to, Rcpp::Nullable<Rcpp::Function> progress, double reportEvery);
RcppExport SEXP _imply_applyOverMarginSparse(SEXP maskSEXP, SEXP valuesSEXP, SEXP dimSEXP, SEXP spatialSEXP, SEXP marginSEXP, SEXP funSEXP, SEXP callNamesSEXP, SEXP simplifySEXP, SEXP fromSEXP, SEXP toSEXP, SEXP progressSEXP, SEXP reportEverySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type margin(marginSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type fun(funSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type callNames(callNamesSEXP);
    Rcpp::traits::input_parameter< bool >::type simplify(simplifySEXP);
    Rcpp::traits::input_parameter< double >::type from(fromSEXP);
    Rcpp::traits::input_parameter< double >::type to(toSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::Function> >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< double >::type reportEvery(reportEverySEXP);
    rcpp_result_gen = Rcpp::wrap(applyOverMarginSparse(mask, values, dim, spatial, margin, fun, callNames, simplify, from, to, progress, reportEvery));
    return rcpp_result_gen;
END_RCPP
}
// pointsToVoxel
Rcpp::NumericMatrix pointsToVoxel(Rcpp::NumericMatrix locs, Rcpp::NumericMatrix xform, Rcpp::NumericVector pixdim, std::string type);
RcppExport SEXP _imply_pointsToVoxel(SEXP locsSEXP, SEXP xformSEXP, SEXP pixdimSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xform(xformSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pixdim(pixdimSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(pointsToVoxel(locs, xform, pixdim, type));
    return rcpp_result_gen;
END_RCPP
}
// pointsFromVoxel
Rcpp::NumericMatrix pointsFromVoxel(Rcpp::NumericMatrix locs, Rcpp::NumericMatrix xform, Rcpp::NumericVector pixdim, std::string type);
RcppExport SEXP _imply_pointsFromVoxel(SEXP locsSEXP, SEXP xformSEXP, SEXP pixdimSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xform(xformSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pixdim(pixdimSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(pointsFromVoxel(locs, xform, pixdim, type));
    return rcpp_result_gen;
END_RCPP
}
// roundPoints
Rcpp::NumericMatrix roundPoints(Rcpp::NumericMatrix locs, std::string round, Rcpp::Nullable<Rcpp::NumericVector> bounds);
RcppExport SEXP _imply_roundPoints(SEXP locsSEXP, SEXP roundSEXP, SEXP boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< std::string >::type round(roundSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type bounds(boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(roundPoints(locs, round, bounds));
    return rcpp_result_gen;
END_RCPP
}
// valueRange
Rcpp::List valueRange(Rcpp::RObject x);
RcppExport SEXP _imply_valueRange(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(valueRange(x));
    return rcpp_result_gen;
END_RCPP
}
// calibrateStorage
Rcpp::List calibrateStorage(std::string type, double low, double high, bool integral);
RcppExport SEXP _imply_calibrateStorage(SEXP typeSEXP, SEXP lowSEXP, SEXP highSEXP, SEXP integralSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type low(lowSEXP);
    Rcpp::traits::input_parameter< double >::type high(highSEXP);
    Rcpp::traits::input_parameter< bool >::type integral(integralSEXP);
    rcpp_result_gen = Rcpp::wrap(calibrateStorage(type, low, high, integral));
    return rcpp_result_gen;
END_RCPP
}
// packNarrow
Rcpp::RawVector packNarrow(Rcpp::RObject x, std::string type, double slope, double intercept);
RcppExport SEXP _imply_packNarrow(SEXP xSEXP, SEXP typeSEXP, SEXP slopeSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< double >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(packNarrow(x, type, slope, intercept));
    return rcpp_result_gen;
END_RCPP
}
// unpackNarrow
Rcpp::NumericVector unpackNarrow(Rcpp::RawVector packed, std::string type, double count, double slope, double intercept);
RcppExport SEXP _imply_unpackNarrow(SEXP packedSEXP, SEXP typeSEXP, SEXP countSEXP, SEXP slopeSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type packed(packedSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type count(countSEXP);
    Rcpp::traits::input_parameter< double >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< double >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(unpackNarrow(packed, type, count, slope, intercept));
    return rcpp_result_gen;
END_RCPP
}
// narrowElements
Rcpp::NumericVector narrowElements(Rcpp::RawVector packed, std::string type, double count, Rcpp::NumericVector indices, double slope, double intercept);
RcppExport SEXP _imply_narrowElements(SEXP packedSEXP, SEXP typeSEXP, SEXP countSEXP, SEXP indicesSEXP, SEXP slopeSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type packed(packedSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type count(countSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< double >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< double >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(narrowElements(packed, type, count, indices, slope, intercept));
    return rcpp_result_gen;
END_RCPP
}
// narrowSummary
Rcpp::List narrowSummary(Rcpp::RawVector packed, std::string type, double count, double slope, double intercept, bool naRm);
RcppExport SEXP _imply_narrowSummary(SEXP packedSEXP, SEXP typeSEXP, SEXP countSEXP, SEXP slopeSEXP, SEXP interceptSEXP, SEXP naRmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type packed(packedSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type count(countSEXP);
    Rcpp::traits::input_parameter< double >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< double >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< bool >::type naRm(naRmSEXP);
    rcpp_result_gen = Rcpp::wrap(narrowSummary(packed, type, count, slope, intercept, naRm));
    return rcpp_result_gen;
END_RCPP
}
// rasterInfo
SEXP rasterInfo(Rcpp::RObject x, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_rasterInfo(SEXP xSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(rasterInfo(x, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// flattenIndices
SEXP flattenIndices(Rcpp::RObject x, Rcpp::IntegerMatrix locs, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_flattenIndices(SEXP xSEXP, SEXP locsSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(flattenIndices(x, locs, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// expandIndices
SEXP expandIndices(Rcpp::RObject x, Rcpp::NumericVector indices, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_expandIndices(SEXP xSEXP, SEXP indicesSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(expandIndices(x, indices, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// lineSums
SEXP lineSums(Rcpp::RObject x, int dim, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic);
RcppExport SEXP _imply_lineSums(SEXP xSEXP, SEXP dimSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    rcpp_result_gen = Rcpp::wrap(lineSums(x, dim, spatial, forceDynamic));
    return rcpp_result_gen;
END_RCPP
}
// blockPartition
SEXP blockPartition(Rcpp::RObject x, Rcpp::Nullable<Rcpp::IntegerVector> spatial, double targetElements, int count);
RcppExport SEXP _imply_blockPartition(SEXP xSEXP, SEXP spatialSEXP, SEXP targetElementsSEXP, SEXP countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< double >::type targetElements(targetElementsSEXP);
    Rcpp::traits::input_parameter< int >::type count(countSEXP);
    rcpp_result_gen = Rcpp::wrap(blockPartition(x, spatial, targetElements, count));
    return rcpp_result_gen;
END_RCPP
}
// parallelInfo
Rcpp::List parallelInfo();
RcppExport SEXP _imply_parallelInfo() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(parallelInfo());
    return rcpp_result_gen;
END_RCPP
}
// chunkPartition
SEXP chunkPartition(double items, int threads);
RcppExport SEXP _imply_chunkPartition(SEXP itemsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type items(itemsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(chunkPartition(items, threads));
    return rcpp_result_gen;
END_RCPP
}
// permuteView
SEXP permuteView(Rcpp::RObject x, Rcpp::IntegerVector order, Rcpp::Nullable<Rcpp::IntegerVector> spatial, bool forceDynamic, int threads);
RcppExport SEXP _imply_permuteView(SEXP xSEXP, SEXP orderSEXP, SEXP spatialSEXP, SEXP forceDynamicSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type order(orderSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< bool >::type forceDynamic(forceDynamicSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(permuteView(x, order, spatial, forceDynamic, threads));
    return rcpp_result_gen;
END_RCPP
}
// dataAddress
std::string dataAddress(Rcpp::RObject x);
RcppExport SEXP _imply_dataAddress(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dataAddress(x));
    return rcpp_result_gen;
END_RCPP
}
// reduceOverMargin
Rcpp::NumericVector reduceOverMargin(Rcpp::RObject x, Rcpp::IntegerVector margin, std::string what, bool naRm, int threads);
RcppExport SEXP _imply_reduceOverMargin(SEXP xSEXP, SEXP marginSEXP, SEXP whatSEXP, SEXP naRmSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type margin(marginSEXP);
    Rcpp::traits::input_parameter< std::string >::type what(whatSEXP);
    Rcpp::traits::input_parameter< bool >::type naRm(naRmSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(reduceOverMargin(x, margin, what, naRm, threads));
    return rcpp_result_gen;
END_RCPP
}
// reduceOverMarginPacked
Rcpp::NumericVector reduceOverMarginPacked(Rcpp::RawVector values, std::string type, Rcpp::IntegerVector dim, Rcpp::IntegerVector margin, std::string what, double slope, double intercept, bool naRm, int threads);
RcppExport SEXP _imply_reduceOverMarginPacked(SEXP valuesSEXP, SEXP typeSEXP, SEXP dimSEXP, SEXP marginSEXP, SEXP whatSEXP, SEXP slopeSEXP, SEXP interceptSEXP, SEXP naRmSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type margin(marginSEXP);
    Rcpp::traits::input_parameter< std::string >::type what(whatSEXP);
    Rcpp::traits::input_parameter< double >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< double >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< bool >::type naRm(naRmSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(reduceOverMarginPacked(values, type, dim, margin, what, slope, intercept, naRm, threads));
    return rcpp_result_gen;
END_RCPP
}
// reduceOverMarginSparse
Rcpp::NumericVector reduceOverMarginSparse(Rcpp::RawVector mask, Rcpp::RObject values, Rcpp::IntegerVector dim, int spatial, Rcpp::IntegerVector margin, std::string what, bool naRm, int threads);
RcppExport SEXP _imply_reduceOverMarginSparse(SEXP maskSEXP, SEXP valuesSEXP, SEXP dimSEXP, SEXP spatialSEXP, SEXP marginSEXP, SEXP whatSEXP, SEXP naRmSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type margin(marginSEXP);
    Rcpp::traits::input_parameter< std::string >::type what(whatSEXP);
    Rcpp::traits::input_parameter< bool >::type naRm(naRmSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(reduceOverMarginSparse(mask, values, dim, spatial, margin, what, naRm, threads));
    return rcpp_result_gen;
END_RCPP
}
// denseToSparse
Rcpp::List denseToSparse(Rcpp::RObject x, Rcpp::Nullable<Rcpp::IntegerVector> spatial);
RcppExport SEXP _imply_denseToSparse(SEXP xSEXP, SEXP spatialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spatial(spatialSEXP);
    rcpp_result_gen = Rcpp::wrap(denseToSparse(x, spatial));
    return rcpp_result_gen;
END_RCPP
}
// sparseToDense
SEXP sparseToDense(Rcpp::RawVector mask, Rcpp::RObject values, Rcpp::IntegerVector dim, int spatial);
RcppExport SEXP _imply_sparseToDense(SEXP maskSEXP, SEXP valuesSEXP, SEXP dimSEXP, SEXP spatialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type spatial(spatialSEXP);
    rcpp_result_gen = Rcpp::wrap(sparseToDense(mask, values, dim, spatial));
    return rcpp_result_gen;
END_RCPP
}
// sparseElements
SEXP sparseElements(Rcpp::RawVector mask, Rcpp::RObject values, Rcpp::IntegerVector dim, int spatial, Rcpp::NumericVector indices);
RcppExport SEXP _imply_sparseElements(SEXP maskSEXP, SEXP valuesSEXP, SEXP dimSEXP, SEXP spatialSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(sparseElements(mask, values, dim, spatial, indices));
    return rcpp_result_gen;
END_RCPP
}
// maskCount
double maskCount(Rcpp::RawVector mask, double locations);
RcppExport SEXP _imply_maskCount(SEXP maskSEXP, SEXP locationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< double >::type locations(locationsSEXP);
    rcpp_result_gen = Rcpp::wrap(maskCount(mask, locations));
    return rcpp_result_gen;
END_RCPP
}
// maskToLogical
Rcpp::LogicalVector maskToLogical(Rcpp::RawVector mask, double locations);
RcppExport SEXP _imply_maskToLogical(SEXP maskSEXP, SEXP locationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< double >::type locations(locationsSEXP);
    rcpp_result_gen = Rcpp::wrap(maskToLogical(mask, locations));
    return rcpp_result_gen;
END_RCPP
}
// maskFromLogical
Rcpp::RawVector maskFromLogical(Rcpp::LogicalVector present);
RcppExport SEXP _imply_maskFromLogical(SEXP presentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type present(presentSEXP);
    rcpp_result_gen = Rcpp::wrap(maskFromLogical(present));
    return rcpp_result_gen;
END_RCPP
}
// maskCombine
Rcpp::RawVector maskCombine(Rcpp::RawVector first, Rcpp::RawVector second, std::string how);
RcppExport SEXP _imply_maskCombine(SEXP firstSEXP, SEXP secondSEXP, SEXP howSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type first(firstSEXP);
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type second(secondSEXP);
    Rcpp::traits::input_parameter< std::string >::type how(howSEXP);
    rcpp_result_gen = Rcpp::wrap(maskCombine(first, second, how));
    return rcpp_result_gen;
END_RCPP
}
// tightenMask
Rcpp::List tightenMask(Rcpp::RawVector mask, Rcpp::RObject values, double locations, double elements);
RcppExport SEXP _imply_tightenMask(SEXP maskSEXP, SEXP valuesSEXP, SEXP locationsSEXP, SEXP elementsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< double >::type locations(locationsSEXP);
    Rcpp::traits::input_parameter< double >::type elements(elementsSEXP);
    rcpp_result_gen = Rcpp::wrap(tightenMask(mask, values, locations, elements));
    return rcpp_result_gen;
END_RCPP
}
// repackValues
SEXP repackValues(Rcpp::RawVector oldMask, Rcpp::RObject values, Rcpp::RawVector newMask, double locations, double elements);
RcppExport SEXP _imply_repackValues(SEXP oldMaskSEXP, SEXP valuesSEXP, SEXP newMaskSEXP, SEXP locationsSEXP, SEXP elementsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type oldMask(oldMaskSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type newMask(newMaskSEXP);
    Rcpp::traits::input_parameter< double >::type locations(locationsSEXP);
    Rcpp::traits::input_parameter< double >::type elements(elementsSEXP);
    rcpp_result_gen = Rcpp::wrap(repackValues(oldMask, values, newMask, locations, elements));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_imply_applyOverMargin", (DL_FUNC) &_imply_applyOverMargin, 9},
    {"_imply_applyOverMarginPacked", (DL_FUNC) &_imply_applyOverMarginPacked, 13},
    {"_imply_applyOverMarginSparse", (DL_FUNC) &_imply_applyOverMarginSparse, 12},
    {"_imply_pointsToVoxel", (DL_FUNC) &_imply_pointsToVoxel, 4},
    {"_imply_pointsFromVoxel", (DL_FUNC) &_imply_pointsFromVoxel, 4},
    {"_imply_roundPoints", (DL_FUNC) &_imply_roundPoints, 3},
    {"_imply_valueRange", (DL_FUNC) &_imply_valueRange, 1},
    {"_imply_calibrateStorage", (DL_FUNC) &_imply_calibrateStorage, 4},
    {"_imply_packNarrow", (DL_FUNC) &_imply_packNarrow, 4},
    {"_imply_unpackNarrow", (DL_FUNC) &_imply_unpackNarrow, 5},
    {"_imply_narrowElements", (DL_FUNC) &_imply_narrowElements, 6},
    {"_imply_narrowSummary", (DL_FUNC) &_imply_narrowSummary, 6},
    {"_imply_rasterInfo", (DL_FUNC) &_imply_rasterInfo, 3},
    {"_imply_flattenIndices", (DL_FUNC) &_imply_flattenIndices, 4},
    {"_imply_expandIndices", (DL_FUNC) &_imply_expandIndices, 4},
    {"_imply_lineSums", (DL_FUNC) &_imply_lineSums, 4},
    {"_imply_blockPartition", (DL_FUNC) &_imply_blockPartition, 4},
    {"_imply_parallelInfo", (DL_FUNC) &_imply_parallelInfo, 0},
    {"_imply_chunkPartition", (DL_FUNC) &_imply_chunkPartition, 2},
    {"_imply_permuteView", (DL_FUNC) &_imply_permuteView, 5},
    {"_imply_dataAddress", (DL_FUNC) &_imply_dataAddress, 1},
    {"_imply_reduceOverMargin", (DL_FUNC) &_imply_reduceOverMargin, 5},
    {"_imply_reduceOverMarginPacked", (DL_FUNC) &_imply_reduceOverMarginPacked, 9},
    {"_imply_reduceOverMarginSparse", (DL_FUNC) &_imply_reduceOverMarginSparse, 8},
    {"_imply_denseToSparse", (DL_FUNC) &_imply_denseToSparse, 2},
    {"_imply_sparseToDense", (DL_FUNC) &_imply_sparseToDense, 4},
    {"_imply_sparseElements", (DL_FUNC) &_imply_sparseElements, 5},
    {"_imply_maskCount", (DL_FUNC) &_imply_maskCount, 2},
    {"_imply_maskToLogical", (DL_FUNC) &_imply_maskToLogical, 2},
    {"_imply_maskFromLogical", (DL_FUNC) &_imply_maskFromLogical, 1},
    {"_imply_maskCombine", (DL_FUNC) &_imply_maskCombine, 3},
    {"_imply_tightenMask", (DL_FUNC) &_imply_tightenMask, 4},
    {"_imply_repackValues", (DL_FUNC) &_imply_repackValues, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_imply(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
