# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rasterInfo <- function(x, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_rasterInfo`, x, spatial, forceDynamic)
}

flattenIndices <- function(x, locs, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_flattenIndices`, x, locs, spatial, forceDynamic)
}

expandIndices <- function(x, indices, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_expandIndices`, x, indices, spatial, forceDynamic)
}

lineSums <- function(x, dim, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_lineSums`, x, dim, spatial, forceDynamic)
}

blockPartition <- function(x, spatial = NULL, targetElements = 65536, count = 0L) {
    .Call(`_imply_blockPartition`, x, spatial, targetElements, count)
}

permuteView <- function(x, order, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_permuteView`, x, order, spatial, forceDynamic)
}

dataAddress <- function(x) {
    .Call(`_imply_dataAddress`, x)
}

