# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

applyOverMargin <- function(x, margin, fun, callNames = NULL, simplify = TRUE, from = 0, to = -1) {
    .Call(`_imply_applyOverMargin`, x, margin, fun, callNames, simplify, from, to)
}

orientationFromXform <- function(xform) {
    .Call(`_imply_orientationFromXform`, xform)
}

invertXform <- function(xform) {
    .Call(`_imply_invertXform`, xform)
}

pointsToVoxel <- function(locs, xform, pixdim, type = "world") {
    .Call(`_imply_pointsToVoxel`, locs, xform, pixdim, type)
}

pointsFromVoxel <- function(locs, xform, pixdim, type = "world") {
    .Call(`_imply_pointsFromVoxel`, locs, xform, pixdim, type)
}

roundPoints <- function(locs, round = "conventional", bounds = NULL) {
    .Call(`_imply_roundPoints`, locs, round, bounds)
}

rasterInfo <- function(x, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_rasterInfo`, x, spatial, forceDynamic)
}

flattenIndices <- function(x, locs, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_flattenIndices`, x, locs, spatial, forceDynamic)
}

expandIndices <- function(x, indices, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_expandIndices`, x, indices, spatial, forceDynamic)
}

lineSums <- function(x, dim, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_lineSums`, x, dim, spatial, forceDynamic)
}

blockPartition <- function(x, spatial = NULL, targetElements = 65536, count = 0L) {
    .Call(`_imply_blockPartition`, x, spatial, targetElements, count)
}

parallelInfo <- function() {
    .Call(`_imply_parallelInfo`)
}

chunkPartition <- function(items, threads) {
    .Call(`_imply_chunkPartition`, items, threads)
}

permuteView <- function(x, order, spatial = NULL, forceDynamic = FALSE, threads = 0L) {
    .Call(`_imply_permuteView`, x, order, spatial, forceDynamic, threads)
}

dataAddress <- function(x) {
    .Call(`_imply_dataAddress`, x)
}

