# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

applyOverMargin <- function(x, margin, fun, callNames = NULL, simplify = TRUE, from = 0, to = -1, progress = NULL, reportEvery = 0) {
    .Call(`_imply_applyOverMargin`, x, margin, fun, callNames, simplify, from, to, progress, reportEvery)
}

applyOverMarginPacked <- function(values, type, dim, margin, fun, slope = 1, intercept = 0, callNames = NULL, simplify = TRUE, from = 0, to = -1, progress = NULL, reportEvery = 0) {
    .Call(`_imply_applyOverMarginPacked`, values, type, dim, margin, fun, slope, intercept, callNames, simplify, from, to, progress, reportEvery)
}

applyOverMarginSparse <- function(mask, values, dim, spatial, margin, fun, callNames = NULL, simplify = TRUE, from = 0, to = -1, progress = NULL, reportEvery = 0) {
    .Call(`_imply_applyOverMarginSparse`, mask, values, dim, spatial, margin, fun, callNames, simplify, from, to, progress, reportEvery)
}

reduceOverMargin <- function(x, margin, what, naRm = FALSE, threads = 0L) {
    .Call(`_imply_reduceOverMargin`, x, margin, what, naRm, threads)
}

reduceOverMarginPacked <- function(values, type, dim, margin, what, slope = 1, intercept = 0, naRm = FALSE, threads = 0L) {
    .Call(`_imply_reduceOverMarginPacked`, values, type, dim, margin, what, slope, intercept, naRm, threads)
}

reduceOverMarginSparse <- function(mask, values, dim, spatial, margin, what, naRm = FALSE, threads = 0L) {
    .Call(`_imply_reduceOverMarginSparse`, mask, values, dim, spatial, margin, what, naRm, threads)
}

orientationFromXform <- function(xform) {
    .Call(`_imply_orientationFromXform`, xform)
}

invertXform <- function(xform) {
    .Call(`_imply_invertXform`, xform)
}

pointsToVoxel <- function(locs, xform, pixdim, type = "world") {
    .Call(`_imply_pointsToVoxel`, locs, xform, pixdim, type)
}

pointsFromVoxel <- function(locs, xform, pixdim, type = "world") {
    .Call(`_imply_pointsFromVoxel`, locs, xform, pixdim, type)
}

roundPoints <- function(locs, round = "conventional", bounds = NULL) {
    .Call(`_imply_roundPoints`, locs, round, bounds)
}

rasterInfo <- function(x, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_rasterInfo`, x, spatial, forceDynamic)
}

flattenIndices <- function(x, locs, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_flattenIndices`, x, locs, spatial, forceDynamic)
}

expandIndices <- function(x, indices, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_expandIndices`, x, indices, spatial, forceDynamic)
}

lineSums <- function(x, dim, spatial = NULL, forceDynamic = FALSE) {
    .Call(`_imply_lineSums`, x, dim, spatial, forceDynamic)
}

blockPartition <- function(x, spatial = NULL, targetElements = 65536, count = 0L) {
    .Call(`_imply_blockPartition`, x, spatial, targetElements, count)
}

parallelInfo <- function() {
    .Call(`_imply_parallelInfo`)
}

chunkPartition <- function(items, threads) {
    .Call(`_imply_chunkPartition`, items, threads)
}

permuteView <- function(x, order, spatial = NULL, forceDynamic = FALSE, threads = 0L) {
    .Call(`_imply_permuteView`, x, order, spatial, forceDynamic, threads)
}

dataAddress <- function(x) {
    .Call(`_imply_dataAddress`, x)
}

valueRange <- function(x) {
    .Call(`_imply_valueRange`, x)
}

calibrateStorage <- function(type, low, high, integral) {
    .Call(`_imply_calibrateStorage`, type, low, high, integral)
}

packNarrow <- function(x, type, slope = 1, intercept = 0) {
    .Call(`_imply_packNarrow`, x, type, slope, intercept)
}

unpackNarrow <- function(packed, type, count, slope = 1, intercept = 0) {
    .Call(`_imply_unpackNarrow`, packed, type, count, slope, intercept)
}

narrowElements <- function(packed, type, count, indices, slope = 1, intercept = 0) {
    .Call(`_imply_narrowElements`, packed, type, count, indices, slope, intercept)
}

narrowSummary <- function(packed, type, count, slope = 1, intercept = 0, naRm = FALSE) {
    .Call(`_imply_narrowSummary`, packed, type, count, slope, intercept, naRm)
}

denseToSparse <- function(x, spatial = NULL) {
    .Call(`_imply_denseToSparse`, x, spatial)
}

sparseToDense <- function(mask, values, dim, spatial) {
    .Call(`_imply_sparseToDense`, mask, values, dim, spatial)
}

sparseElements <- function(mask, values, dim, spatial, indices) {
    .Call(`_imply_sparseElements`, mask, values, dim, spatial, indices)
}

maskCount <- function(mask, locations) {
    .Call(`_imply_maskCount`, mask, locations)
}

maskToLogical <- function(mask, locations) {
    .Call(`_imply_maskToLogical`, mask, locations)
}

maskFromLogical <- function(present) {
    .Call(`_imply_maskFromLogical`, present)
}

maskCombine <- function(first, second, how) {
    .Call(`_imply_maskCombine`, first, second, how)
}

tightenMask <- function(mask, values, locations, elements) {
    .Call(`_imply_tightenMask`, mask, values, locations, elements)
}

repackValues <- function(oldMask, values, newMask, locations, elements) {
    .Call(`_imply_repackValues`, oldMask, values, newMask, locations, elements)
}

